### ISSUE TITLE
Documentation question, does this project support parameter encryption ?

### ISSUE THREAD

**Issue by smbambling** [Jeoffreybauvin/puppenc#51]

**Comment by Jeoffreybauvin** [comment]
Hi @smbambling,

I'm not sure what you are talking about. What parameter encryption ?

**Comment by smbambling** [comment]
Does the project have the ability to encrypt secret data like passwords with a GPG key or a passphrase ?

**Comment by Jeoffreybauvin** [comment]
No, Puppenc doesn't support encryption, and it's not supposed to. It's a node classifier, not a storage for encryption data. You shouldn't store any secret in it :).
